function createfigure_affinity_matrix(cdata1, cdata2, cdata3, cdata4)
%CREATEFIGURE(CDATA1, CDATA2, CDATA3, CDATA4)
%  CDATA1:  image cdata
%  CDATA2:  image cdata
%  CDATA3:  image cdata
%  CDATA4:  image cdata

%  Auto-generated by MATLAB on 24-Jun-2020 21:40:04

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create subplot
subplot1 = subplot(1,4,1,'Parent',figure1);
hold(subplot1,'on');

% Create image
image(cdata1,'Parent',subplot1,'CDataMapping','scaled');

% Create title
title({'(a) Ground truth'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[0.5 100.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[0.5 100.5]);
box(subplot1,'on');
axis(subplot1,'ij');
% Set the remaining axes properties
set(subplot1,'Layer','top','XTick',zeros(1,0),'YTick',zeros(1,0));
% Create subplot
subplot2 = subplot(1,4,2,'Parent',figure1);
hold(subplot2,'on');

% Create image
image(cdata2,'Parent',subplot2,'CDataMapping','scaled');

% Create title
title({'(b) L1 affinity'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[0.5 100.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[0.5 100.5]);
box(subplot2,'on');
axis(subplot2,'ij');
% Set the remaining axes properties
set(subplot2,'Layer','top','XTick',zeros(1,0),'YTick',zeros(1,0));
% Create subplot
subplot3 = subplot(1,4,3,'Parent',figure1);
hold(subplot3,'on');

% Create image
image(cdata3,'Parent',subplot3,'CDataMapping','scaled');

% Create title
title({'(c) L1 affinity + diffusion'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot3,[0.5 100.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot3,[0.5 100.5]);
box(subplot3,'on');
axis(subplot3,'ij');
% Set the remaining axes properties
set(subplot3,'Layer','top','XTick',zeros(1,0),'YTick',zeros(1,0));
% Create subplot
subplot4 = subplot(1,4,4,'Parent',figure1);
hold(subplot4,'on');

% Create image
image(cdata4,'Parent',subplot4,'CDataMapping','scaled');

% Create title
title({'(d) L1 affinity + diffusion +','self-supervision'});

% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot4,[0.5 100.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot4,[0.5 100.5]);
box(subplot4,'on');
axis(subplot4,'ij');
% Set the remaining axes properties
set(subplot4,'Layer','top','XTick',zeros(1,0),'YTick',zeros(1,0));
